name: ROS2 CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Setup ROS2
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: humble
            
    - name: Install WiringPi i2c library for RPi 4
      uses: actions/checkout@v4
    - run: |
        mkdir Downloads
        git clone https://github.com/wbeebe/WiringPi.git
        cd WiringPi/
        ./build
    
    - name: Install dependencies for MPU6050 C++ library
      run: sudo apt install libi2c-dev i2c-tools libi2c0
        
    - name: Build Lidarbot packages 
      uses: ros-tooling/action-ros-ci@v0.4
      with:
        package-name: |
          lidarbot
          lidarbot_base
          lidarbot_bringup
          lidarbot_description
          lidarbot_gazebo
          lidarbot_gz
          lidarbot_navigation
          lidarbot_slam
          lidarbot_teleop
        target-ros2-distro: humble
        skip-tests: true

    - name: Upload Logs
      uses: actions/upload-artifact@v4
      with:
        name: colcon-logs
        path: ros_ws/log
      if: always()
