%YAML:1.0
---
image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  dt: d
  data: [842.57825,   0.     , 304.89032,
           0.     , 841.64125, 224.5223 ,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  dt: d
  data: [0.002363, 0.562980, -0.004719, -0.008675, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [862.94263,   0.     , 302.0357 ,   0.     ,
           0.     , 863.9823 , 223.20963,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
